FROM python:3.12

WORKDIR /APP

COPY requirements /app/requirements

RUN pip install --upgrade pip
RUN pip install -r /app/requirements/base.txt

COPY . .

EXPOSE 8000

RUN python manage.py collectstatic --noinput

ENTRYPOINT [ "./start.sh" ]
